# Generated by Django 5.1.12 on 2025-09-23 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0003_post_created_date_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                default=1,  # Replace with the ID of an existing user
                on_delete=models.CASCADE,
                to='auth.user',
            ),
        ),
    ]
